# SAM CLI deploy configuration
# Usage: sam deploy --config-env prod

version = 0.1

[default.deploy.parameters]
stack_name = "pod-scoring-pipeline"
resolve_s3 = true
s3_prefix = "pod-scoring-pipeline"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []

[prod.deploy.parameters]
stack_name = "pod-scoring-prod"
parameter_overrides = "Stage=prod"

[dev.deploy.parameters]
stack_name = "pod-scoring-dev"
parameter_overrides = "Stage=dev"
